# 데이터베이스 설정
# DB 종류
database: h2db
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    #url: jdbc:h2:file:./target/h2db/db/application;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: stamp
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    # DB초기화(schema.sql, data.sql) , [always : 기동 시 매번 동작, never : 기동 시 동작하지 않음]
    init:
      # schema-locations: classpath*:initdata/${database}/schema.sql
      data-locations: classpath*:initdata/${database}/data.sql
      #schema-locations: classpath*:initdata/h2db/schema.sql
      #data-locations: classpath*:initdata/h2db/data.sql
      mode: embedded
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    #jpa 사용 환경에서 data.sql을 정상적으로 동작하게 하는 옵션
    defer-datasource-initialization: true